-- Banco de produtos da Pesos e Medidas
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price text not null,
  category text default '',
  image text default '',
  description text default '',
  sold_out boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Clientes podem somente visualizar o catálogo.
create policy "public can read products"
on public.products for select
to anon, authenticated
using (true);

-- Usuários autenticados (o dono) podem gerenciar produtos.
create policy "authenticated can insert products"
on public.products for insert
to authenticated
with check (true);

create policy "authenticated can update products"
on public.products for update
to authenticated
using (true)
with check (true);

create policy "authenticated can delete products"
on public.products for delete
to authenticated
using (true);
